name: smart_8ball
description: AI backed 8Ball
publish_to: 'none'
version: 0.0.1-dev

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  fluentui_system_icons: ^1.1.198
  sensors: ^2.0.3
  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.1.2
  bloc: ^8.1.1
  envied: ^0.3.0
  permission_handler: ^10.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable: ^2.1.1
  dio: ^5.1.1
  json_annotation: ^4.8.0
  get_it: ^7.2.0
  flutter_form_builder: ^7.8.0
  firebase_core: ^2.9.0
  google_fonts: 4.0.3
  dart_openai: ^1.9.1
  go_router: ^6.5.2
  flutter_glow: 0.2.0
  firebase_auth: ^4.4.0
  form_builder_validators: ^8.5.0
  router:
    path: packages/router
  firebase_analytics: ^10.2.0
  flutter_phoenix: ^1.1.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.5
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

  flutter_lints: ^2.0.1
