name: smart_8ball
description: AI backed 8Ball
publish_to: 'none'
version: 0.0.1-dev

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  fluentui_system_icons: ^1.1.199
  sensors: ^2.0.3
  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.1.2
  bloc: ^8.1.1
  envied: ^0.3.0
  permission_handler: ^10.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable: ^2.1.1
  dio: ^5.1.1
  json_annotation: ^4.8.0
  get_it: ^7.2.0
  flutter_form_builder: ^7.8.0
  firebase_core: ^2.9.0
  google_fonts: 4.0.3
  dart_openai: ^1.9.1
  go_router: ^6.5.6
  flutter_glow: ^0.3.0
  firebase_auth: ^4.4.1
  form_builder_validators: ^8.5.0
  router:
    path: packages/router
  firebase_analytics: ^10.2.0
  flutter_phoenix: ^1.1.1
  firebase_remote_config: ^4.0.0
  cloud_functions: ^4.1.0
  cloud_firestore: ^4.5.1
  device_info_plus: ^8.2.0
  record: ^4.4.4
  google_mobile_ads: ^2.4.0
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.5
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

  flutter_lints: ^2.0.1
  json_serializable: ^6.6.1

flutter:
  fonts:
    - family: Monoton
      fonts:
        - asset: lib/_support/asset/font/Monoton/Monoton-Regular.ttf
    - family: Automania
      fonts:
        - asset: lib/_support/asset/font/Automania/Automania.ttf
    - family: Beon
      fonts:
        - asset: lib/_support/asset/font/Beon/Beon.otf
    - family: LasEnter
      fonts:
        - asset: lib/_support/asset/font/LasEnter/LasEnter.ttf
    - family: TextMeOne
      fonts:
        - asset: lib/_support/asset/font/TextMeOne/TextMeOne-Regular.ttf
    - family: Night-Club-70s
      fonts:
        - asset: lib/_support/asset/font/Night-Club-70s/Night-Club-70s-Bold.ttf
        - asset: lib/_support/asset/font/Night-Club-70s/Night-Club-70s-Regular.ttf
    - family: Membra
      fonts:
        - asset: lib/_support/asset/font/Membra/Membra.ttf
    - family: Samarin
      fonts:
        - asset: lib/_support/asset/font/Samarin/Samarin.ttf
    - family: Cyberpunk
      fonts:
        - asset: lib/_support/asset/font/Cyberpunk/Cyberpunk.ttf